spring.application.name=api-gateway
server.port=8082

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Config service
config.service.url=${CONFIG_SERVICE_URL:http://localhost:8081}

# JWT
jwt.secret=${JWT_SECRET:bToQsL+JRReoNY7FL/uPHbxOa9S6vJxSDAVD37Srz6c=}

# Rate limit defaults
rate.limit.requests=${RATE_LIMIT_REQUESTS:10}
rate.limit.window-seconds=${RATE_LIMIT_WINDOW:60}

#Routes
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
# Logging
logging.level.com.apishield=DEBUG