spring.application.name=api-gateway
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Routes
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/auth/**
jwt.secret=bToQsL+JRReoNY7FL/uPHbxOa9S6vJxSDAVD37Srz6c=
